piece:
  tonic: C
  scale_type: major
  n_voices: 4
  lowest_note: C3
  highest_note: C6
  sonorities_durations:
    # 1st measure
    - 0.5
    - 0.25
    - 0.25
    # 2nd measure
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    # 3rd measure
    - 0.25
    - 0.125
    - 0.125
    - 0.25
    - 0.125
    - 0.125
    # 4th measure
    - 0.5
    - 0.25
    - 0.125
    - 0.125
    # 5th measure
    - 0.5
    - 0.5
    # 6th measure
    - 0.5
    - 0.25
    - 0.25
    # 7th measure
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    # 8th measure
    - 1.0
rendering:
  dir: geniartor_data
  measure_in_seconds: 1.0
  midi:
    instrument: 0
    velocity: 100
  sinethesizer:
    timbre: default_timbre
    volume: 0.3
optimization:
  n_passes: 2
  perturbation_probability: 0.3
evaluation:
  scoring_coefs:
    harmonic_stability: 1
    tonal_stability: 1
  scoring_fn_params:
    harmonic_stability:
      min_stabilities:
        beginning: 0.8
        ending: 0.9
        downbeat: 0.75
        middle: 0.5
        other: 0.25
      n_semitones_to_stability:
        0: 1.0
        1: 0.2
        2: 0.2
        3: 0.7
        4: 0.8
        5: 0.5
        6: 0.0
        7: 0.9
        8: 0.6
        9: 0.6
        10: 0.2
        11: 0.2
    tonal_stability:
      min_stabilities:
        beginning: 0.7
        ending: 0.8
        downbeat: 0.7
        middle: 0.5
        other: 0.2
      degree_to_stability:
        1: 1.0
        2: 0.4
        3: 0.7
        4: 0.4
        5: 0.8
        6: 0.4
        7: 0.0
