piece:
  tonic: C
  scale_type: major
  n_voices: 4
  lowest_note: C4
  highest_note: C6
  sonorities_durations:
    # 1st measure
    - 0.5
    - 0.25
    - 0.25
    # 2nd measure
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    # 3rd measure
    - 0.25
    - 0.125
    - 0.125
    - 0.25
    - 0.125
    - 0.125
    # 4th measure
    - 0.5
    - 0.25
    - 0.125
    - 0.125
    # 5th measure
    - 0.5
    - 0.5
    # 6th measure
    - 0.5
    - 0.25
    - 0.25
    # 7th measure
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    # 8th measure
    - 1.0
rendering:
  dir: geniartor_data
  measure_in_seconds: 1.0
  midi:
    instrument: 0
    velocity: 100
  sinethesizer:
    timbre: default_timbre
    volume: 0.3
optimization:
  n_passes: 5
evaluation:
  scoring_coefs:
    dissipation_of_tension: 1
    melodic_fluency: 1
  scoring_fn_params:
    dissipation_of_tension:
      beat_weights:
        0.0: 1.0
        0.5: 0.5
      n_semitones_to_stability:
        0: 1.0
        1: 0.2
        2: 0.2
        3: 0.7
        4: 0.8
        5: 0.5
        6: 0.0
        7: 0.9
        8: 0.6
        9: 0.6
        10: 0.2
        11: 0.2
    melodic_fluency:
      forces_between_degrees:
        !!python/tuple [1, 1]: 0.0
        !!python/tuple [1, 2]: 0.0
        !!python/tuple [1, 3]: 0.0
        !!python/tuple [1, 4]: 0.0
        !!python/tuple [1, 5]: 0.0
        !!python/tuple [1, 6]: 0.0
        !!python/tuple [1, 7]: 0.0
        !!python/tuple [2, 1]: 1.0
        !!python/tuple [2, 2]: -0.3
        !!python/tuple [2, 3]: 0.2
        !!python/tuple [2, 4]: -0.2
        !!python/tuple [2, 5]: 0.0
        !!python/tuple [2, 6]: -0.4
        !!python/tuple [2, 7]: -0.3
        !!python/tuple [3, 1]: 0.3
        !!python/tuple [3, 2]: 0.3
        !!python/tuple [3, 3]: 0.0
        !!python/tuple [3, 4]: 0.3
        !!python/tuple [3, 5]: 0.3
        !!python/tuple [3, 6]: -0.3
        !!python/tuple [3, 7]: -0.3
        !!python/tuple [4, 1]: 0.2
        !!python/tuple [4, 2]: -0.3
        !!python/tuple [4, 3]: 0.2
        !!python/tuple [4, 4]: -0.3
        !!python/tuple [4, 5]: 0.8
        !!python/tuple [4, 6]: -0.3
        !!python/tuple [4, 7]: -0.3
        !!python/tuple [5, 1]: 0
        !!python/tuple [5, 2]: -0.3
        !!python/tuple [5, 3]: 0.2
        !!python/tuple [5, 4]: 0.3
        !!python/tuple [5, 5]: 0
        !!python/tuple [5, 6]: 0.3
        !!python/tuple [5, 7]: -0.3
        !!python/tuple [6, 1]: 0.0
        !!python/tuple [6, 2]: -0.5
        !!python/tuple [6, 3]: 0.0
        !!python/tuple [6, 4]: -0.3
        !!python/tuple [6, 5]: 0.5
        !!python/tuple [6, 6]: -0.3
        !!python/tuple [6, 7]: 0.2
        !!python/tuple [7, 1]: 1.0
        !!python/tuple [7, 2]: -0.5
        !!python/tuple [7, 3]: -0.5
        !!python/tuple [7, 4]: -0.5
        !!python/tuple [7, 5]: -0.5
        !!python/tuple [7, 6]: 0.2
        !!python/tuple [7, 7]: -0.5
      tolerance: -0.1
